name: Changelog

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Set Release Version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.1
        with:
          release_version: ${{ github.event.inputs.release_version }}
