name: Release
on: [workflow_dispatch]
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
        # - uses: fregante/setup-git-user@v1
      - run: git config --global user.email "markus@malkusch.de"
      - run: git config --global user.name "Markus Malkusch"
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: maven
          server-id: sonatype-nexus-staging
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE }}
      - name: Prepare
        run: mvn --batch-mode release:prepare -Darguments="-DskipTests -Dgpg.keyname=km200@malkusch.de -Dgpg.passphrase=" -DpushChanges=false

      - run: false

      - name: Push
        run: git push
      - run: git push --tags
      - name: Release    
        run: mvn --batch-mode release:perform -DconnectionUrl=scm:git:${{ github.server_url }}/${{ github.repository }} -Darguments="-DskipTests -Dgpg.keyname=km200@malkusch.de -Dgpg.passphrase="
